name: flutter_internet_speed_test
description: A Flutter plugin to test internet download and upload speed.
version: 1.4.1
# authors: [ Shahbaz Akhtar <meshahbaz.akhtar@gmail.com> ]
homepage: https://github.com/shaz-tech/flutter_internet_speed_test

environment:
  sdk: ">=3.1.1 <4.0.0"
  flutter: ">=3.13.3"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3
  tuple_dart: ^1.4.2
  connectivity_plus: ^4.0.2
  http: ^1.1.0
  logger: ^2.0.2

dev_dependencies:

flutter:
  plugin:
    platforms:
      android:
        package: com.shaz.plugin.fist.flutter_internet_speed_test
        pluginClass: FlutterInternetSpeedTestPlugin
      ios:
        pluginClass: FlutterInternetSpeedTestPlugin
